spring:  
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: '{cipher}AQBaFBsbabu018CvCA4O7+fJggfBDVPapR7eRQXagXf7i95BLCHsz8ZEKrpSMNg8bbdSa66s6upFfiZoFLSp8KW9/rUKbfgbGa6JMxJzgEZ+YoKrFrji7XkeOx6kEkxkuhJyG0PHs5UUCSK11/1jRwtFCzDvNUDzHFMPNjLFQ4dBgccW+QCKnd9FzM9sJllaSc6Co05PR1bkfOdjLgJto3T9uKE6Gvj3hEfLO17tApTT2UCtmqlRKnfUhVWdurgrtkpUMpNc8HzSm4Z3MssdwM8igLoQVAvy4FZ2ff4P0nX6364/qNb5k89cfgixN2ywzWgvHe9uHJOUD9TCXAI0dYixW683LphfbtTEvjb0iT6mPp20CbIAb1LtWTI8FwyleKI='

token:
  expiration_time: 864000000
  secret: '{cipher}AQCBUNFhduECbULvHg3FphGCOlieajKuTm5L2fR1H3LWWFBtJY0s+Xw8XWdh7NkX/1R2K4PtkjlAcCxAu5yhFy7pXlizm0aiDzG5pE4JBFANtsnNFrYCFe23ASpgqzkCs0gw4tKqToK+O02UEUSwi7ZH9h778sENxs/E30JO7rqX8RFIo5Yb/RLSvgSWnGq6DqMUGt7TDt3qSCtq4x/TKexPaTbQKCikR5D/SqI7mHLAJrM4CbtN4Y6ZDgrPf8bJPrxqijAhmEQdRpOxdTCwfEI6r8Iv4rHnzY5O3uqk1cadrHwM7KFUuYy77MVWQyIybvfyh0T5PUi5303zVl35OvnMO8ICuEGbQJ63lFWMC49/FdYGSP1Dc2Q2YvkcVKaemYaZGRjFjHfWvudfrXedEGtSe54mg+3uleLb9RlAj4kogQ=='
  #user_token_canonical_ubuntu_main

#gateway:
#  ip: 192.168.0.96
