spring:  
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: '{cipher}AQBaFBsbabu018CvCA4O7+fJggfBDVPapR7eRQXagXf7i95BLCHsz8ZEKrpSMNg8bbdSa66s6upFfiZoFLSp8KW9/rUKbfgbGa6JMxJzgEZ+YoKrFrji7XkeOx6kEkxkuhJyG0PHs5UUCSK11/1jRwtFCzDvNUDzHFMPNjLFQ4dBgccW+QCKnd9FzM9sJllaSc6Co05PR1bkfOdjLgJto3T9uKE6Gvj3hEfLO17tApTT2UCtmqlRKnfUhVWdurgrtkpUMpNc8HzSm4Z3MssdwM8igLoQVAvy4FZ2ff4P0nX6364/qNb5k89cfgixN2ywzWgvHe9uHJOUD9TCXAI0dYixW683LphfbtTEvjb0iT6mPp20CbIAb1LtWTI8FwyleKI=aa'

token:
  expiration_time: 864000000
  secret: user_token_canonical_ubuntu_main

#gateway:
#  ip: 192.168.0.96
